### ISSUE TITLE
GET posts/, post/:id Exception

### ISSUE THREAD

**Issue by pachoulie** [freedonaab/PastaGag#3]
Lorsqu'on veut récupérer les posts ou un post, une erreur survient causées par ces deux lignes du fichier controlles/posts/index.js :
//                _global.post.votes.user_voted_up = _global.votedUp;
//                _global.post.votes.user_voted_down = _global.votedDown;
Du coup, je les ai commenté
Clément, tu peux voir pourquoi ?

**Comment by petitcl** [comment]
yep! je bosserai dessus Mercredi soir et toute la journée de Jeudi, j'en profiterai pour fix ça!

**Comment by petitcl** [comment]
fixed!
